- name: Установить pip3
  apt:
    name: python3-pip
    state: present

- name: Установить PyMySQL
  pip:
    name: PyMySQL
    state: present
    executable: /usr/bin/pip3

- name: Установить MySQL
  apt:
    name: mysql-server
    state: present

- name: Запустить MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Установить root-пароль для MySQL
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost
    priv: '*.*:ALL,GRANT'
    state: present
