- name: Установить MySQL
  apt:
    name: mysql-server
    state: present

- name: Запустить MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Установить root-пароль для MySQL
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL,GRANT'
    state: present
