- name: Установить необходимые пакеты
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Добавить GPG-ключ Docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Добавить репозиторий Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
    filename: docker


- name: Установить Docker
  apt:
    name: docker-ce
    state: present

- name: Запустить Docker
  service:
    name: docker
    state: started
    enabled: yes
