name: Deploy with Ansible

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Установить SSH-ключ
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/server_ssh.pem
          chmod 600 ~/.ssh/server_ssh.pem
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/server_ssh.pem

      - name: Добавление ключа сервера в known_hosts
        run: |
          ssh-keyscan -H 54.145.135.174 >> ~/.ssh/known_hosts
          
      - name: Запуск Ansible playbook
        run: |
          # Выполнение playbook'а
          ansible-playbook -i hosts.ini -u ubuntu --private-key ~/.ssh/server_ssh.pem site.yml || {
            echo "Playbook execution failed, checking Nginx status and logs";
            ssh -i ~/.ssh/server_ssh.pem ubuntu@54.145.135.174 "sudo systemctl status nginx.service";
            ssh -i ~/.ssh/server_ssh.pem ubuntu@54.145.135.174 "sudo journalctl -xeu nginx.service";
            exit 1;
          }
