name: Deploy with Ansible

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Установить SSH-ключ
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Подключение к серверу и деплой
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.145.135.174 "cd /путь/к/проекту && git pull && docker-compose up -d"
